image: proboci/ubuntu:18.04-php7.4
steps:
  - name: Build Arizona Quickstart
    plugin: Script
    script:
      - composer self-update
      - if [ $(git ls-remote --heads https://github.com/az-digital/az_quickstart.git $BRANCH_NAME | wc -l) = 1 ]; then PROFILE_BRANCH="$BRANCH_NAME"; else PROFILE_BRANCH=2.6.x-dev; fi
      - composer require --no-update drupal/core-recommended:* az-digital/az_quickstart:dev-${PROFILE_BRANCH}
      - composer install -o
  - name: Install Arizona Quickstart
    plugin: Drupal
    drupalVersion: 8
    subDirectory: web
    runInstall: true
    profileName: az_quickstart
    installArgs: "--site-name='Quickstart Review' --account-name=azadmin --account-pass=azadmin --verbose --yes -n"
