image: proboci/ubuntu:20.04-php8.1
steps:
  - name: Build Arizona Quickstart
    plugin: Script
    script:
      - composer self-update
      - if [ $(git ls-remote --heads https://github.com/az-digital/az_quickstart.git $BRANCH_NAME | wc -l) = 1 ]; then PROFILE_BRANCH="dev-${BRANCH_NAME}"; else PROFILE_BRANCH=2.8.x-dev; fi
      - if [ $(git ls-remote --heads https://github.com/az-digital/az-quickstart-dev.git $BRANCH_NAME | wc -l) = 1 ]; then DEV_BRANCH="$BRANCH_NAME"; else DEV_BRANCH=main; fi
      - composer require --dev --no-update az-digital/az-quickstart-dev:dev-${DEV_BRANCH}
      - composer require --no-update drupal/core-recommended:* az-digital/az_quickstart:${PROFILE_BRANCH}
      - composer install -o
  - name: Install Arizona Quickstart
    plugin: Drupal
    drupalVersion: 10
    subDirectory: web
    runInstall: true
    profileName: az_quickstart
    installArgs: "--site-name='Quickstart Review' --account-name=azadmin --account-pass=azadmin --verbose --yes -n"
    cliDefines: {DRUSH_LAUNCHER_FALLBACK: '$SRC_DIR/vendor/bin/drush'}
