image: proboci/ubuntu:20.04-php8.1
steps:
  - name: Build Arizona Quickstart
    plugin: Script
    script:
      - composer self-update
      - if [ $(git ls-remote --heads https://github.com/az-digital/az_quickstart.git $BRANCH_NAME | wc -l) = 1 ]; then PROFILE_BRANCH="$BRANCH_NAME"; else PROFILE_BRANCH=2.14.x; fi
      - if [[ ${PROFILE_BRANCH} =~ ^[0-9]\.[0-9x] ]]; then PROFILE_VERSION="${PROFILE_BRANCH}-dev"; else PROFILE_VERSION="dev-${PROFILE_BRANCH}"; fi
      - composer require --no-update drupal/core-recommended:* az-digital/az_quickstart:${PROFILE_VERSION}
      - if [ $(git ls-remote --heads https://github.com/az-digital/az-quickstart-dev.git $BRANCH_NAME | wc -l) = 1 ]; then DEV_BRANCH="$BRANCH_NAME"; else DEV_BRANCH=main; fi
      - if [[ ${DEV_BRANCH} =~ ^[0-9]\.[0-9x] ]]; then DEV_VERSION="${DEV_BRANCH}-dev"; else DEV_VERSION="dev-${DEV_BRANCH}"; fi
      - composer require --dev --no-update az-digital/az-quickstart-dev:${DEV_VERSION}
      - composer install -o
  - name: Install Arizona Quickstart
    plugin: Drupal
    drupalVersion: 10
    subDirectory: web
    runInstall: true
    profileName: az_quickstart
    installArgs: "--site-name='Quickstart Review' --account-name=azadmin --account-pass=azadmin2025 --verbose --yes -n"
    cliDefines: {DRUSH_LAUNCHER_FALLBACK: '$SRC_DIR/vendor/bin/drush'}
