#!/bin/sh

## Description: Run the az_quickstart installation inside the web container.
## Usage: quickstart-install
## Example: "ddev quickstart-install"

drush --root=/var/www/html/web site:install --account-mail=noreply@email.arizona.edu --account-name=azadmin --account-pass=azadmin --db-url=mysql://db:db@db:3306/db -y --verbose
drush --root=/var/www/html/web config:set -y az_cas.settings disable_login_form 0
drush --root=/var/www/html/web cache:rebuild
